ALTER TABLE "League" DROP COLUMN IF EXISTS "name";
ALTER TABLE "League" DROP COLUMN IF EXISTS "type";
ALTER TABLE "League" DROP COLUMN IF EXISTS "country";
ALTER TABLE "League" DROP COLUMN IF EXISTS "updatedAt";
